/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-05-09 07:01:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DingDan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1511510250091L));
    _jspx_dependants.put("jar:file:/F:/WorkSpace/wuliu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wuliu/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1503365862614L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	request.setAttribute("basePath", basePath);
	String realPath=request.getSession().getServletContext().getRealPath("/");
	request.setAttribute("sessionname", request.getSession().getAttribute("username"));

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>网上下订单</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("client/css/reset.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("client/css/common.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("client/css/thems.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!--头部-->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("<!--头部-->\r\n");
      out.write("<!--中间部分-->\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\t<div class=\"book\">\r\n");
      out.write("    \t<div class=\"tabBox_t\">\r\n");
      out.write("            <div class=\"tabBox\">\r\n");
      out.write("              <ul class=\"tabNav\">\r\n");
      out.write("                <li class=\"now\"><em>网上下单</em><span>&nbsp;</span></li>\r\n");
      out.write("                <li><a href=\"\">网点查询</a></li>\r\n");
      out.write("                <li><a href=\"\">货物追踪</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"tabCont\" style=\"display:block;\">\r\n");
      out.write("              \t<div class=\"book_m\">\r\n");
      out.write("                \t<div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("                \t<!-- <div class=\"shunxu\">\r\n");
      out.write("                    \t<img src=\"images/icon6.jpg\" alt=\"\"/>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("                    <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/client/buildBill\" method=\"post\">\r\n");
      out.write("                    <div class=\"fahuo\">\r\n");
      out.write("                    \t<span>\r\n");
      out.write("                    \t发货城市\r\n");
      out.write("                    \t<input id=\"zhhuoDD\" name=\"zhhuoDD\" type=\"text\" placeholder=\"请输入城市名（中文/拼音）\">\r\n");
      out.write("\t\t\t                        到达城市\r\n");
      out.write("\t\t\t            <input id=\"xihuoDD\" name=\"xihuoDD\" type=\"text\" placeholder=\"请输入城市名（中文/拼音）\"></br>\r\n");
      out.write("\t\t\t                        物品信息\r\n");
      out.write("\t\t\t            <input id=\"huowuXX\" name=\"huowuXX\" type=\"text\" placeholder=\"请输入物品信息（中文/拼音）\">\r\n");
      out.write("\t\t\t                        物品重量\r\n");
      out.write("\t\t\t            <input id=\"huowuZL\" name=\"huowuZL\" type=\"text\" placeholder=\"请输入物品重量（kg）\"></br>\r\n");
      out.write("\t\t\t                        物品大小\r\n");
      out.write("\t\t\t            <input id=\"huowuDX\" name=\"huowuDX\" type=\"text\" placeholder=\"请输入物品体积（m^3）\">\r\n");
      out.write("\t\t\t                        物品数量\r\n");
      out.write("\t\t\t            <input id=\"huowuSL\" name=\"huowuSL\" type=\"text\" placeholder=\"请输入物品个数（个/件）\"></br>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("                    <ul class=\"xinxi\">\r\n");
      out.write("                        <li class=\"shuxing\">\r\n");
      out.write("                        \t<span>增值服务</span>\r\n");
      out.write("                            <input name=\"\" class=\"check\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                            防倾斜\r\n");
      out.write("                            <input name=\"\" class=\"check\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                            防撞\r\n");
      out.write("                            <input name=\"\" class=\"check\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                            易碎\r\n");
      out.write("                            <input name=\"\" class=\"check\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                            不能堆叠\r\n");
      out.write("                            <input name=\"\" class=\"check\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                            不能分拆\r\n");
      out.write("                            <input name=\"\" class=\"check\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                            不能倒置\r\n");
      out.write("                            <input name=\"\" class=\"check\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                            正本回单\r\n");
      out.write("                            <input name=\"\" class=\"check\" type=\"checkbox\" value=\"\">\r\n");
      out.write("                            高价值\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("                    <table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                      \r\n");
      out.write("                      <tr class=\"wl_title\">\r\n");
      out.write("                        <td width=\"50\" class=\"tubiao\"></td>\r\n");
      out.write("                        <td width=\"85\">物品种类</td>\r\n");
      out.write("                        <td width=\"150\">线路</td>\r\n");
      out.write("                        <td width=\"90\">泡货<em>元/公斤</em></td>\r\n");
      out.write("                        <td width=\"90\">重泡货<em>元/公斤</em></td>\r\n");
      out.write("                        <td width=\"90\">重货<em>元/公斤</em></td>\r\n");
      out.write("                        <td width=\"90\">最低收费</td>\r\n");
      out.write("                        <td width=\"70\">时效</td>\r\n");
      out.write("                        <td width=\"85\">承运件数</td>\r\n");
      out.write("                        <td width=\"65\"></td>\r\n");
      out.write("                        <td width=\"67\"></td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                     \r\n");
      out.write("                    \r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("                    <div class=\"txxx clearfix\">\r\n");
      out.write("                    \r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("            <!--发货人信息-->\r\n");
      out.write("            <div class=\"txxx_l\">\r\n");
      out.write("                        \t<div class=\"txxx_h\">\r\n");
      out.write("                            \t<span>发货人信息</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                            \t<li>\r\n");
      out.write("                                \t<span>\r\n");
      out.write("                                    \t<i>&nbsp;</i>\r\n");
      out.write("                                        发货人\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <input id=\"fahuoXM\" name=\"fahuoXM\" type=\"text\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                \t<span>\r\n");
      out.write("                                        手机\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <input id=\"fahuoDH\" name=\"fahuoDH\" type=\"text\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <!-- \r\n");
      out.write("                                <li>\r\n");
      out.write("                                \t<span>\r\n");
      out.write("                                    \t<i>&nbsp;</i>\r\n");
      out.write("                                        发货地址\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <input id=\"\" name=\"\" type=\"text\" placeholder=\"请选择/输入城市名称\">\r\n");
      out.write("                                    <input id=\"\" name=\"\" class=\"jiedao\" type=\"text\" placeholder=\"请输入街道地址\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                                 -->\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--发货人信息-->\r\n");
      out.write("                        \r\n");
      out.write("                        <!--收货人信息-->\r\n");
      out.write("                        <div class=\"txxx_r\">\r\n");
      out.write("                        \t<div class=\"txxx_h\">\r\n");
      out.write("                            \t<span>收货人信息</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                            \t<li>\r\n");
      out.write("                                \t<span>\r\n");
      out.write("                                    \t<i>&nbsp;</i>\r\n");
      out.write("                                        收货人\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <input id=\"shhuoXM\" name=\"shhuoXM\" type=\"text\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                \t<span>\r\n");
      out.write("                                        手机\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <input id=\"shhuoDH\" name=\"shhuoDH\" type=\"text\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                     \r\n");
      out.write("                                <!-- \r\n");
      out.write("                                <li>\r\n");
      out.write("                                \t<span>\r\n");
      out.write("                                    \t<i>&nbsp;</i>\r\n");
      out.write("                                                       收货地址\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <input id=\"\" name=\"\" type=\"text\" placeholder=\"请选择/输入城市名称\">\r\n");
      out.write("                                    <input id=\"\" class=\"jiedao\" name=\"\" type=\"text\" placeholder=\"请输入街道地址\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                                 -->\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--收货人信息-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("                    <div class=\"tiaok\">\r\n");
      out.write("                    \t<span><input name=\"\" type=\"checkbox\" value=\"\" checked>统一服务条款</span>\r\n");
      out.write("                        <textarea name=\"\" cols=\"\" rows=\"\">\r\n");
      out.write("1.托运人应准确填写本单，如实告知承运人所托运货物的名称、性质、重量、数量、价值等必要情况；托与人应对所托运获取按照行业标准妥善包装，使其适合运输.\r\n");
      out.write("2.托运人应准确填写本单，如实告知承运人所托运货物的名称、性质、重量、数量、价值等必要情况；托与人应对所托运获取按照行业标准妥善包装，使其适合运输.\r\n");
      out.write("                        </textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("                    <div class=\"xiadan_btn\">\r\n");
      out.write("                    \t<input type=\"submit\" class=\"sub\" value=\"生成运单\">\r\n");
      out.write("                        <!-- <a href=\"\" class=\"qux\">取消</a> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--中间部分-->\r\n");
      out.write("<div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("<!--底部-->\r\n");
      out.write("<div class=\"foot_bg\">\r\n");
      out.write("\t<div class=\"foot\">\r\n");
      out.write("    \t<div class=\"foot_t\">\r\n");
      out.write("        \t<a href=\"\">业务介绍</a>\r\n");
      out.write("            <a href=\"\">联系我们</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copy\">\r\n");
      out.write("        \tCopyright&copy;&nbsp;2012-2015&nbsp;\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\t\r\n");
      out.write("</div>\r\n");
      out.write("<!--底部-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
