/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-03-13 15:23:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FaBu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1511510250091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	request.setAttribute("basePath", basePath);
	String realPath=request.getSession().getServletContext().getRealPath("/");
	request.setAttribute("sessionname", request.getSession().getAttribute("username"));

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>发布运单</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("client/css/reset.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("client/css/common.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("client/css/thems.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("client/js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--头部-->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("<!--头部-->\r\n");
      out.write("<!-- 中间 -->\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\t<!--订单中心-->\r\n");
      out.write("    <div class=\"order clearfix\">\r\n");
      out.write("    \t<div class=\"order_l\">\r\n");
      out.write("        \t<ul id=\"left_menu\" class=\"left_menu\">\r\n");
      out.write("            \t<li>\r\n");
      out.write("                \t<a class=\"yiji\"><span>XX物流运单</span><em>&nbsp;</em></a>\r\n");
      out.write("                    <ul class=\"erji\">\r\n");
      out.write("                    \t<li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">基本信息</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">运单信息</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                \t<a class=\"yiji\"><span>订单中心</span><em>&nbsp;</em></a>\r\n");
      out.write("                    <ul class=\"erji\">\r\n");
      out.write("                    \t<li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">我的订单</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">我的账单</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">代收货款</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">资金流水</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">询价历史</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">常发货物</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        \t<i>&nbsp;</i>\r\n");
      out.write("                            <strong><a href=\"\">常用联系人</a></strong>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"order_r\">\r\n");
      out.write("        \t<div class=\"order_h\">\r\n");
      out.write("            \t<span>基本信息</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("           <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            <ul class=\"my_zil\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <span>发货人信息：</span>\r\n");
      out.write("                    <a href=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.fahuoXM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <span>地址：</span>\r\n");
      out.write("                    <a href=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.zhhuoDD}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <span>联系电话：</span>\r\n");
      out.write("                    <a href=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.fahuoDH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>\r\n");
      out.write("            <ul class=\"my_zil\">\r\n");
      out.write("               <li>\r\n");
      out.write("                    <span>收货人信息：</span>\r\n");
      out.write("                    <a href=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.shhuoXM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <span>地址：</span>\r\n");
      out.write("                    <a href=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.xihuoDD}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <span>联系电话：</span>\r\n");
      out.write("                    <a href=\"\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.shhuoDH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("                </li> \r\n");
      out.write("                </ul>\r\n");
      out.write("            </td>\t   \r\n");
      out.write("           </tr>\r\n");
      out.write("            <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("            <div class=\"order_news\">\r\n");
      out.write("            \t<span>运单信息</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \t <table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                      <tr class=\"wl_title\">\r\n");
      out.write("                        <td width=\"60\" class=\"tubiao\">订单号</td>\r\n");
      out.write("                        <td width=\"85\">物品名称</td>\r\n");
      out.write("                        <td width=\"180\">线路</td>\r\n");
      out.write("                        <td width=\"90\">货物重量<em>元/公斤</em></td>\r\n");
      out.write("                        <td width=\"110\">重泡货<em>元/公斤</em></td>\r\n");
      out.write("                        <td width=\"90\">重货<em>元/公斤</em></td>\r\n");
      out.write("                        <td width=\"80\">货物数量</td>\r\n");
      out.write("                        <td width=\"65\">总费用</td>\r\n");
      out.write("                      </tr>\r\n");
      out.write("                      <tr>\r\n");
      out.write("                        <td><a href=\"\" class=\"fav\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.yundanH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" &nbsp;</a></td>\r\n");
      out.write("                        <td class=\"left\">\r\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.huowuXX}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"left\">\r\n");
      out.write("                            <span>从： ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.zhhuoDD}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                            <span>到： ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.xihuoDD}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><i>0.15</i></td>\r\n");
      out.write("                        <td><i>0.12</i></td>\r\n");
      out.write("                        <td><i>20</i>元</td>\r\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.huowuSL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        <td><i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SESSION_YUNDAN.yundaFY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("元</i></td>\r\n");
      out.write("                       \r\n");
      out.write("                      </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--订单中心-->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("      <div class=\"book_m\" >\r\n");
      out.write("                <div class=\"xiadan_btn\" >\r\n");
      out.write("                        <a href=\"\" class=\"sub\">付款</a>\r\n");
      out.write("                        <a href=\"\" class=\"qux\">取消订单</a> \r\n");
      out.write("                </div>         \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--中间部分-->\r\n");
      out.write("<div class=\"space_hx\">&nbsp;</div>\r\n");
      out.write("<!--底部-->\r\n");
      out.write("<div class=\"foot_bg\">\r\n");
      out.write("\t<div class=\"foot\">\r\n");
      out.write("    \t<div class=\"foot_t\">\r\n");
      out.write("        \t<a href=\"\">业务介绍</a>\r\n");
      out.write("            <a href=\"\">联系我们</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"copy\">\r\n");
      out.write("        \tCopyright&copy;&nbsp;2012-2015&nbsp; 找物流有限责任公司.&nbsp;&nbsp;All&nbsp;&nbsp;rights&nbsp;&nbsp;reserved. &nbsp;&nbsp;粤ICP备10005645\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\t\r\n");
      out.write("</div>\r\n");
      out.write("<!--底部-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
