/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-12-08 13:39:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.backgroud.zj;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class zj_005fJymx_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1511510250091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	request.setAttribute("basePath", basePath);
	String realPath=request.getSession().getServletContext().getRealPath("/");
	request.setAttribute("sessionname", request.getSession().getAttribute("username"));

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>XXXX物流管理系统 - 发布运单</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/css/css.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/js/jquery1.9.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/js/sdmenu.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/js/laydate/laydate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../left.jsp", out, false);
      out.write("\r\n");
      out.write("  <div class=\"right\"  id=\"mainFrame\">\r\n");
      out.write("     \r\n");
      out.write("     <div class=\"right_cont\">\r\n");
      out.write("<ul class=\"breadcrumb\">当前位置：\r\n");
      out.write("  <a href=\"#\">首页</a> <span class=\"divider\">/</span>\r\n");
      out.write("  <a href=\"#\">资金处理</a> <span class=\"divider\">/</span>\r\n");
      out.write("  交易明细\r\n");
      out.write("</ul>\r\n");
      out.write("   \r\n");
      out.write("   <div class=\"title_right\"><strong>运单明细</strong></div>  \r\n");
      out.write("       <div style=\"width:900px; margin:auto\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">运单号：</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"23%\">12345678</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">发货地址：</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"23%\">0000000000</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">收货地址：</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"23%\">00000000000</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">交易时间：</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"23%\">2017-10-11</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">结束时间：</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"23%\">2017-11-11</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">运单交易状态：</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"23%\">已完成</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered table-hover table-striped\">\r\n");
      out.write("         <tbody>\r\n");
      out.write("           <tr align=\"center\">\r\n");
      out.write("             <td><strong>No</strong></td>\r\n");
      out.write("             <td><strong>运单货物名称</strong></td>\r\n");
      out.write("             <td><strong>货物种类</strong></td>\r\n");
      out.write("             <td><strong>大小</strong></td>\r\n");
      out.write("             <td><strong>重量</strong></td>\r\n");
      out.write("             <td><strong>费用金额</strong></td>\r\n");
      out.write("             <td><strong>运送车辆</strong></td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr align=\"center\">\r\n");
      out.write("             <td>1</td>\r\n");
      out.write("             <td>102001151</td>\r\n");
      out.write("             <td>18701</td>\r\n");
      out.write("             <td>110517</td>\r\n");
      out.write("             <td>12</td>\r\n");
      out.write("             <td>2017</td>\r\n");
      out.write("             <td><a id=\"DataGrid1_ctl03_LinkButton1\" href=\"javascript:__doPostBack('DataGrid1$ctl03$LinkButton1','')\">详细</a></td>\r\n");
      out.write("             <td>完成</td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr align=\"center\">\r\n");
      out.write("             <td>2</td>\r\n");
      out.write("             <td>华南城分理处</td>\r\n");
      out.write("             <td>1637</td>\r\n");
      out.write("             <td>151776</td>\r\n");
      out.write("             <td>12</td>\r\n");
      out.write("             <td>2017</td>\r\n");
      out.write("             <td>蒙B12138</td>\r\n");
      out.write("             <td><a id=\"DataGrid1_ctl04_LinkButton1\" href=\"javascript:__doPostBack('DataGrid1$ctl04$LinkButton1','')\">详细</a></td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr align=\"center\">\r\n");
      out.write("             <td>3</td>\r\n");
      out.write("             <td>102001151</td>\r\n");
      out.write("             <td>18701</td>\r\n");
      out.write("             <td>110517</td>\r\n");
      out.write("             <td>12</td>\r\n");
      out.write("             <td>2017</td>\r\n");
      out.write("             <td>完成</td>\r\n");
      out.write("             <td><a id=\"DataGrid1_ctl03_LinkButton1\" href=\"javascript:__doPostBack('DataGrid1$ctl03$LinkButton1','')\">详细</a></td>\r\n");
      out.write("           </tr>\r\n");
      out.write("         </tbody>\r\n");
      out.write("         \t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">收货人：</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"23%\">12345678</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">发货人：</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"23%\">0000000000</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"10%\" align=\"right\" nowrap=\"nowrap\" bgcolor=\"#f1f1f1\">总费用：</td>\r\n");
      out.write("\t\t\t\t\t\t<td>00000000000</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("       </table>\r\n");
      out.write(" \t  \t\r\n");
      out.write("    <!--  \r\n");
      out.write("     <tr>\r\n");
      out.write("       <td class=\"text-center\"><input type=\"button\" value=\"打印\" class=\"btn btn-info    margin-right-20\" style=\"width:80px;\"  /><input type=\"button\" value=\"数据导出\" class=\"btn btn-info  \"  style=\"width:80px;\" /></td>\r\n");
      out.write("     </tr>-->\r\n");
      out.write("   </div>\r\n");
      out.write("     </div>     \r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!-- 底部 -->\r\n");
      out.write("<div id=\"footer\">版权所有：&nbsp;&nbsp;&nbsp;&nbsp;</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("!function(){\r\n");
      out.write("laydate.skin('molv');\r\n");
      out.write("laydate({elem: '#Calendar'});\r\n");
      out.write("laydate.skin('molv');\r\n");
      out.write("laydate({elem: '#Calendar2'});\r\n");
      out.write("}();\r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
