/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-04-26 02:47:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.backgroud;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1511510250091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	request.setAttribute("basePath", basePath);
	String realPath=request.getSession().getServletContext().getRealPath("/");
	request.setAttribute("sessionname", request.getSession().getAttribute("username"));

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>XXXX物流管理系统</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/css/bootstrap.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/css/css.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/js/jquery1.9.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/js/sdmenu.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/js/laydate/laydate.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/img/logo.png\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t<i class=\"icon-question-sign icon-white\"></i> <a href=\"#\">帮助</a> <i\r\n");
      out.write("\t\t\t\tclass=\"icon-off icon-white\"></i> <a id=\"modal-973558\"\r\n");
      out.write("\t\t\t\thref=\"#modal-container-973558\" role=\"button\" data-toggle=\"modal\">注销</a>\r\n");
      out.write("\t\t\t<i class=\"icon-user icon-white\"></i> <a href=\"#\">开票员的工作平台</a> <i\r\n");
      out.write("\t\t\t\tclass=\"icon-envelope icon-white\"></i> <a href=\"#\">发送短信</a>\r\n");
      out.write("\t\t\t<div id=\"modal-container-973558\" class=\"modal hide fade\"\r\n");
      out.write("\t\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 300px; margin-left: -150px; top: 30%\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t\t<h3 id=\"myModalLabel\">注销系统</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<p>您确定要注销退出系统吗？</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">关闭</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-primary\" style=\"line-height: 20px;\"\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/admin/loginout\">确定退出</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 顶部 -->\r\n");
      out.write("\t<!-- 左侧 -->\r\n");
      out.write("\t<div id=\"middle\">\r\n");
      out.write("\t\t<div class=\"left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tvar myMenu;\r\n");
      out.write("\t\t\t\twindow.onload = function() {\r\n");
      out.write("\t\t\t\t\tmyMenu = new SDMenu(\"my_menu\");\r\n");
      out.write("\t\t\t\t\tmyMenu.init();\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"my_menu\" class=\"sdmenu\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span>业务处理</span> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Ydck.jsp\">运单仓库</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Ydfh.jsp\">运单复核</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Ydxg.jsp\">运单修改</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Hwfp.jsp\">货物分配</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Fbyd.jsp\">发布运单</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Qhqd.jsp\">取货清单</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Chqd.jsp\">出货清单</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Dhqr.jsp\">到货确认</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/yw/yw_Yfjs.jsp\">运费结算</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>数据统计</span> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/zj/zj_Jytj.jsp\">综合统计</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/zj/zj_Khtj.jsp\">客户统计</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/zj/zj_Sjtj.jsp\">司机统计</a> <a href=\"#\">收款详单</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">每日汇总</a> <a href=\"#\">车辆运费</a> <a href=\"#\">线路运量</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>司机管理</span> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/sj/sj_Sjgl.jsp\">司机管理</a><a href=\"#\">基本资料管理</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">维修管理</a> <a href=\"#\">加油管理</a> <a href=\"#\">保养记录</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">派车管理</a> <a href=\"#\">派车记录</a> <a href=\"#\">包车分账</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">月分账</a> <a href=\"#\">事故业务</a> <a href=\"#\">保险业务</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">行驶证</a> <a href=\"#\">营运证</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>客户管理</span> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("backgroud/kh/kh_khgl.jsp\">客户管理</a><a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">客户投诉</a> <a href=\"#\">投诉处理</a> <a href=\"#\">投诉查询</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">客户关怀</a> <a href=\"#\">积分查询</a> <a href=\"#\">分理处排行</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">理赔申请</a> <a href=\"#\">理赔审核</a> <a href=\"#\">理赔结算</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">理赔查询</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>资金结算</span> <a href=\"#\">提货登记</a> <a href=\"#\">收款核销</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">现金转账</a> <a href=\"#\">现付结算</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>票据查询</span> <a href=\"#\">票据查询</a> <a href=\"#\">跟踪查询</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">车次查询</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>系统管理</span> <a href=\"#\">线路管理</a> <a href=\"#\">手续费设置</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">更改密码</a> <a href=\"#\">系统日志</a> <a href=\"#\">帐号管理</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">复核设置</a> <a href=\"#\">部门管理</a> <a href=\"#\">角色管理</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">用户管理</a> <a href=\"#\">短信设置</a> <a href=\"#\">短信发送</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">分理处分成设置</a> <a href=\"#\">省价格设置</a> <a href=\"#\">市价格设置</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">县价格设置</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>中转处理</span> <a href=\"#\">中转操作</a> <a href=\"#\">中转单修改</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">当日中转明细</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>财务管理</span> <a href=\"#\">分公司日报</a> <a href=\"#\">科目管理</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">费用录入</a> <a href=\"#\">费用统计</a> <a href=\"#\">当日对账</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">往日对账</a> <a href=\"#\">利润分成</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>单据管理</span> <a href=\"#\">作废挂失</a> <a href=\"#\">取消修改</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">修改清单</a> <a href=\"#\">退单管理</a> <a href=\"#\">运单修改查询</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">运单修改</a> <a href=\"#\">异常处理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>行政办公</span> <a href=\"#\">文件管理</a> <a href=\"#\">在线留言</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">人事管理</a> <a href=\"#\">公告管理</a> <a href=\"#\">罚款登记</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">滚动字幕</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>工资及包车费管理</span> <a href=\"#\">工资管理</a> <a href=\"#\">包车费管理</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">房租管理</a> <a href=\"#\">货场费管理</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"collapsed\">\r\n");
      out.write("\t\t\t\t\t<span>领导决策</span> <a href=\"#\">新增客户分析</a> <a href=\"#\">长期未发货分析</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">同比业务分析</a> <a href=\"#\">环比业务分析</a> <a href=\"#\">超期预警</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"Switch\"></div>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function(e) {\r\n");
      out.write("\t\t\t\t$(\".Switch\").click(function() {\r\n");
      out.write("\t\t\t\t\t$(\".left\").toggle();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 左侧 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 右侧 -->\r\n");
      out.write("\t\t<!-- 右侧 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 底部 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
