/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-02-12 12:39:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.appPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1511510250091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	request.setAttribute("basePath", basePath);
	String realPath=request.getSession().getServletContext().getRealPath("/");
	request.setAttribute("sessionname", request.getSession().getAttribute("username"));

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>兴趣小队社交网站</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/css/base.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/css/index.css\" />\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/js/move.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/js/xunlei.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--头部菜单-->\r\n");
      out.write("\t\t<div class=\"top\"> \r\n");
      out.write("\t\t    <div class=\"w t_cen\">\r\n");
      out.write("\t\t        <div class=\"t_c_logo\"><a href=\"index.jsp\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/logo.png\" /></a></div>\r\n");
      out.write("\t\t        <div class=\"t_c_lr t_c_left\"></div>\r\n");
      out.write("\t\t        <div class=\"t_c_cen\">\r\n");
      out.write("\t\t            <div class=\"t_c_top\">\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            <div class=\"t_c_bottom\">\r\n");
      out.write("\t\t                <ul>\r\n");
      out.write("\t\t                    <li class=\"thisli\">\r\n");
      out.write("\t\t                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/welcome.jsp\"><em>兴趣首页</em><i>Home</i></a>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/index.jsp\"><em>兴趣中心</em><i>Interest </i></a>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/replay/mood\"><em>兴趣日志</em><i>Journal</i></a>\r\n");
      out.write("\t\t                        <div class=\"Nodes\">\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_top.png\" />\r\n");
      out.write("\t\t                            <ul>\r\n");
      out.write("\t\t                                <li><a href=\"#\">类型1</a></li>\r\n");
      out.write("\t\t                                <li><a href=\"#\">类型2</a></li>\r\n");
      out.write("\t\t                                <li><a href=\"#\">类型3</a></li>\r\n");
      out.write("\t\t                                <li><a href=\"#\">类型4</a></li>\r\n");
      out.write("\t\t                            </ul>\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_bottom.png\" />\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/article.jsp\"><em>兴趣小组</em><i>Group </i></a>\r\n");
      out.write("\t\t                        <div class=\"Nodes\">\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_top.png\" />\r\n");
      out.write("\t\t                            <ul>\r\n");
      out.write("\t\t                                <li><a href=\"#\">小组1</a></li>\r\n");
      out.write("\t\t                                <li><a href=\"#\">小组2</a></li>\r\n");
      out.write("\t\t                                <li><a href=\"#\">小组3</a></li>\r\n");
      out.write("\t\t                            </ul>\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_bottom.png\" />\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/replay/jump\"><em>留言板</em><i> Board</i></a>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                    \r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/group/jump\"><em>小组管理</em><i>Manage</i></a>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                    <li>\r\n");
      out.write("\t\t                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/friend/jump\"><em>个人中心</em><i>My Center</i></a>\r\n");
      out.write("\t\t                        <div class=\"Nodes\">\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_top.png\">\r\n");
      out.write("\t\t                            <ul>\r\n");
      out.write("\t\t                           \t    <li><a href=\"#\">个人详情</a></li>\r\n");
      out.write("\t\t                                <li><a href=\"#\">个人信息</a></li>\r\n");
      out.write("\t\t                            </ul>\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_bottom.png\" />\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                    </li>\r\n");
      out.write("\t\t                    \r\n");
      out.write("\t\t                    \t");

		                    		if(session.getAttribute("SESSION_INSIDERINFO") == null){
		                    	
      out.write("\r\n");
      out.write("\t\t                    \t<li>\r\n");
      out.write("\t\t                        <a href=\"#\"><em>登录注册</em><i>Join Us</i></a>\r\n");
      out.write("\t\t                          <div class=\"Nodes\">\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_top.png\" />\r\n");
      out.write("\t\t                            <ul>\r\n");
      out.write("\t\t                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/login.jsp#toregister\">点击注册</a></li>\r\n");
      out.write("\t\t                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/login.jsp\">点击登录</a></li>\r\n");
      out.write("\t\t                            </ul>\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_bottom.png\" />\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        </li>\r\n");
      out.write("\t\t                        ");

		                    		}else{
		                        
      out.write("\r\n");
      out.write("\t\t                        <li>\r\n");
      out.write("\t\t                         <a href=\"#\"><em>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.SESSION_INSIDERINFO.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</em><i>Join Us</i></a>\r\n");
      out.write("\t\t                          <div class=\"Nodes\">\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_top.png\" />\r\n");
      out.write("\t\t                            <ul>\r\n");
      out.write("\t\t                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/about.jsp\">个人中心</a></li>\r\n");
      out.write("\t\t                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/regist/logout\">退出</a></li>\r\n");
      out.write("\t\t                            </ul>\r\n");
      out.write("\t\t                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/images/menu_bottom.png\" />\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                         </li>\r\n");
      out.write("\t\t                         ");
 
		                        	 } 
		                         
      out.write("\r\n");
      out.write("\t\t                </ul>\r\n");
      out.write("\t\t                <div class=\"thisMenu\" id=\"thisMenu\"></div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <div class=\"t_c_lr t_c_right\"></div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!--/头部菜单-->\r\n");
      out.write("\r\n");
      out.write("<!--引用JQuery-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/js/jquery.js\"></script>\r\n");
      out.write("<!-- <!--其他样式-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("appPage/js/Other.js\"></script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
