/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2018-03-05 15:35:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.driver;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/common.jsp", Long.valueOf(1511510250091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
	request.setAttribute("basePath", basePath);
	String realPath=request.getSession().getServletContext().getRealPath("/");
	request.setAttribute("sessionname", request.getSession().getAttribute("username"));

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"icon\" href=\"images/logo.ico\">\r\n");
      out.write("<title>XXXX物流-首页</title>\r\n");
      out.write("<meta name=\"description\" content=\"XXXX物流实现了车找货、货找车的实时连接，通过互联网服务于广大货运司机和相关货运的各界人。XXXX物流坚持社会效益始终第一的原则，服务质量期待你的关注，希望一路与你同行，共创美好的未来！\">\r\n");
      out.write("<meta name=\"keywords\" content=\"XXXX物流,物流,XXXX物流,货运,货运联盟\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("driver/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("driver/css/style.css\">\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"js/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--导航-开始-->\r\n");
      out.write("<nav class=\"navbar navbar-default\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li class=\"active\"><a href=\"#\">首页<span class=\"sr-only\"></span></a></li>\r\n");
      out.write("                <li><a href=\"alliance.html\">联盟简介</a></li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">货运信息<span class=\"caret\"></span></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"freight-info.html\">货运信息发布</a></li>\r\n");
      out.write("                        <li><a href=\"freight-details.html\">货运信息详情</a></li>\r\n");
      out.write("                        <li><a href=\"freight-map.html\">货运地图</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">司机读本<span class=\"caret\"></span></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"driving-knowledge.html\">驾驶常识</a></li>\r\n");
      out.write("                        <li><a href=\"driving-knowledge.html\">政策法规</a></li>\r\n");
      out.write("                        <li><a href=\"driving-knowledge.html\">卡车评估</a></li>\r\n");
      out.write("                        <li><a href=\"driving-knowledge.html\">修车指导</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">行内互动<span class=\"caret\"></span></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"line-interaction.html\">驾驶员记分</a></li>\r\n");
      out.write("                        <li><a href=\"line-interaction.html\">卡车求购转让</a></li>\r\n");
      out.write("                        <li><a href=\"line-interaction.html\">招聘信息</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"contact-us.html\">联系我们</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!--导航-结束-->\r\n");
      out.write("\r\n");
      out.write("<!--内容-开始-->\r\n");
      out.write("<!--货源信息-->\r\n");
      out.write("<div class=\"container\"><!--广告-->\r\n");
      out.write("\t<a href=\"\" target=\"_blank\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("driver/images/ggt_03.png\" class=\"img-responsive\" style=\"width:100%; height:auto;\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\"><!--货源信息-->\r\n");
      out.write("    <h3>货源信息</h3>\r\n");
      out.write("    <table class=\"table table-bordered\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>出发地</th>\r\n");
      out.write("                <th>到达地</th>\r\n");
      out.write("                <th>货物描述</th>\r\n");
      out.write("                <th>意向价格</th>\r\n");
      out.write("                <th>发布时间</th>\r\n");
      out.write("                <th>状态</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody id=\"list\">\r\n");
      out.write("              \r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\"><!--货源地图-->\r\n");
      out.write("\t<h3>货运地图</h3>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<!--<hr class=\"featurette-divider\">\t-->\r\n");
      out.write("<div class=\"container\"><!--司机读本、行内互动-->\r\n");
      out.write("\t<div class=\"row\" style=\"margin:0;\">\r\n");
      out.write("    \t<div class=\"col-sm-5\" style=\"border:1px solid #ccc;\">\r\n");
      out.write("            <div class=\"row reader\">\r\n");
      out.write("            \t<h3 class=\"driver\"><img src=\"images/reader driver.png\"> <span> 司机读本</span></h3>\r\n");
      out.write("            \t<div class=\"col-md-3 col-xs-6\">\r\n");
      out.write("                \t<a href=\"\">\r\n");
      out.write("                    \t<img src=\"images/tubiao_03.png\" class=\"img-circle\">\r\n");
      out.write("                        <p>驾驶常识</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-xs-6\">\r\n");
      out.write("                \t<a href=\"\">\r\n");
      out.write("                    \t<img src=\"images/tubiao_09.png\" class=\"img-circle\"><p>政策法规</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-xs-6\">\r\n");
      out.write("                \t<a href=\"\"><img src=\"images/trucks.png\" class=\"img-circle\"><p>卡车评估</p></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-3 col-xs-6\">\r\n");
      out.write("                \t<a href=\"\"><img src=\"images/06.png\" class=\"img-circle\"><p>修车指导</p></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-5 col-sm-offset-2\" style=\"border:1px solid #ccc;\">\r\n");
      out.write("            <div class=\"row line\">\r\n");
      out.write("            \t<h3 class=\"driver\" style=\" background:#FA8686;\"><img src=\"images/line interaction.png\"> <span> 行内互动</span></h3>\r\n");
      out.write("            \t<div class=\"col-md-4 col-xs-6\">\r\n");
      out.write("                \t<a href=\"\">\r\n");
      out.write("                    \t<img src=\"images/ttubiao_08.png\" class=\"img-circle\">\r\n");
      out.write("                        <p>驾照分数</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 col-xs-6\">\r\n");
      out.write("                \t<a href=\"\">\r\n");
      out.write("                    \t<img src=\"images/ttubiao_10.png\" class=\"img-circle\">\r\n");
      out.write("                        <p>车辆交易</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 col-xs-6\">\r\n");
      out.write("                \t<a href=\"\">\r\n");
      out.write("                    \t<img src=\"images/ttubiao_12.png\" class=\"img-circle\">\r\n");
      out.write("                   \t    <p>招聘信息</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--内容-结束-->\r\n");
      out.write("<div class=\"container\"><!--广告-->\r\n");
      out.write("\t<a href=\"\" target=\"_blank\"><img src=\"images/gg_03.jpg\" class=\"img-responsive\" style=\"width:100%; height:auto; margin:20px 0;\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--尾部-开始-->\r\n");
      out.write("<div class=\"footer\" style=\"background:#525252; width:100%; padding-bottom:20px; margin-top:30px;\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-4\">\r\n");
      out.write("                <p>友情链接</p>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <ul>\r\n");
      out.write("                   <li><a href=\"\" target=\"_blank\">中国物流网</a></li>\r\n");
      out.write("                   <li><a href=\"\" target=\"_blank\">中国物流网</a></li>\r\n");
      out.write("                   <li><a href=\"\" target=\"_blank\">中国物流网</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-4\">\r\n");
      out.write("                <p>XXXX物流</p>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <p>XXXX物流成立于2013年，是一家专业提供互联网物流信息的网站。</p>\r\n");
      out.write("                <p>XXXX物流实现了车找货、货找车的实时连接，通过互联网服务于广大货运司机和相关货运的各界人士。</p>\r\n");
      out.write("                <p>XXXX物流坚持社会效益始终第一的原则，服务质量期待你的关注，希望一路与你同行，共创美好的未来！</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-4\">\r\n");
      out.write("                <p><a href=\"contact-us.html\">加盟我们</a> | <a href=\"contact-us.html\">联系我们</a></p>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <p>咨询电话：13462264663</p>\r\n");
      out.write("                <p>邮箱：xinguanghuoyun@163.com</p>\r\n");
      out.write("                <p>地址：河南省新乡市八一路35号中同街办事处</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-12 text-center\" style=\"margin-top:20px;\">\r\n");
      out.write("            \tCopyright ©  XXXX物流 版权所有 Power by www.xghylm.com  更多模板：<a href=\"http://www.mycodes.net/\" target=\"_blank\">源码之家</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--尾部-结束-->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("driver/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("driver/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script >\r\n");
      out.write(" function show(){\r\n");
      out.write("\t var hstr=\"\";\r\n");
      out.write("\t $.ajax({\r\n");
      out.write("\t\t url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"+\"app/driver/listPage\",\r\n");
      out.write("\t\t success:function(data){\r\n");
      out.write("\t\t\t for (var i = 0; i < data.length; i++) {\r\n");
      out.write("\t\t\t\tvar str=\"<tr><form id='search_form' name='search_form' action='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/list/pageDetail' method='get'>\"\r\n");
      out.write("\t\t\t\t+\" <td>\"+data[i].zhhuoDD+\"</td>\"\r\n");
      out.write("\t\t\t\t+\" <td>\"+data[i].xihuoDD+\"</td>\"\r\n");
      out.write("\t\t\t\t+\" <td>\"+data[i].huowuXX+\"</td>\"\r\n");
      out.write("\t\t\t\t+\" <td>\"+data[i].yundaFY+\"元</td>\"\r\n");
      out.write("\t\t\t\t+\" <td>\"+data[i].yundaSJ+\"</td>\"\r\n");
      out.write("\t\t\t\t+\" <td class='see'><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("app/driver/qiangdan?\"+data[i].yundanH+\"'>抢单</td>\"\r\n");
      out.write("\t\t\t\t+\"</form></tr>\";\r\n");
      out.write("\t\t\t\thstr += str;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t $(\"#list\").html(hstr);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t });\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" </script>\r\n");
      out.write(" <script>\r\n");
      out.write(" $(function(){\r\n");
      out.write("\t\t// 初始化用户树\r\n");
      out.write("\t\tshow();\r\n");
      out.write("\t});\r\n");
      out.write(" </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
